# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bctl < Formula
  desc "BotKube CLI is a command line tool that helps you migrate your Botkube installation to Botkube Cloud."
  homepage "https://botkube.io"
  version "0.0.0-rc.7"
  license "MIT"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huseyinbabal/botkube/releases/download/v0.0.0-rc.7/botkube_0.0.0-rc.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "284cc8bc98e89e2184184479a7c33da4b067f0c0ee3ba7d9990d89fefd2f1b7f"

      def install
        bin.install "botkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/huseyinbabal/botkube/releases/download/v0.0.0-rc.7/botkube_0.0.0-rc.7_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ae6d120416169125921e8383c103385fe47d2ffd1dcb958562487426946b52cb"

      def install
        bin.install "botkube"
      end
    end
  end
end
