# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botkube < Formula
  desc "BotKube CLI is a command line tool that helps you migrate your Botkube installation to Botkube Cloud."
  homepage "https://botkube.io"
  version "0.0.0-rc.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/huseyinbabal/botkube/releases/download/v0.0.0-rc.12/botkube_0.0.0-rc.12_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d027ddbdc2692b725458a88802e8aab31634fbffc7de60fa8edaa4b7e9e7749d"

      def install
        bin.install "botkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/huseyinbabal/botkube/releases/download/v0.0.0-rc.12/botkube_0.0.0-rc.12_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ce4978961eb2167a860c9d58fa67f2c3825d81b063dcf2f5a9c039d7db63cd07"

      def install
        bin.install "botkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huseyinbabal/botkube/releases/download/v0.0.0-rc.12/botkube_0.0.0-rc.12_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "65b4afeb847589cd0b06e3e0e3b9ca34b2d6316d762c6f37f646dc008aa3097f"

      def install
        bin.install "botkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/huseyinbabal/botkube/releases/download/v0.0.0-rc.12/botkube_0.0.0-rc.12_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b339b02b78b1617efe56807f4c4980363decdbac6b09cefbce630c7ddf5e6247"

      def install
        bin.install "botkube"
      end
    end
  end
end
