# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swiss < Formula
  desc "Swiss army knife for Developer's daily basis tools e.g. Base64 encode/decode, password generator"
  homepage "https://github.com/huseyinbabal/swiss"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/huseyinbabal/swiss/releases/download/0.0.6/swiss_0.0.6_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "848b2f56b83528c5c3c595618be3aacc18bd55fbf1b6f8b39e4fe74cd5dc37c5"

      define_method(:install) do
        bin.install "swiss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/huseyinbabal/swiss/releases/download/0.0.6/swiss_0.0.6_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7d8c1631b344871dd38fa391d66f28224e39b0e849c9db010ebdbdd7a60d4fbe"

      define_method(:install) do
        bin.install "swiss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/huseyinbabal/swiss/releases/download/0.0.6/swiss_0.0.6_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c429b83837a1d3056998476e20d10205528278bf59861ceacf2852ab2ae237f3"
      define_method(:install) do
        bin.install "swiss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huseyinbabal/swiss/releases/download/0.0.6/swiss_0.0.6_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "522bfe7f5a6b0efb3037e0e9595ce232f1d78b68bc2d8c66939ff167b8cd52b3"
      define_method(:install) do
        bin.install "swiss"
      end
    end
  end
end
