# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swiss < Formula
  desc "Swiss army knife for Developer's daily basis tools e.g. Base64 encode/decode, password generator"
  homepage "https://github.com/huseyinbabal/swiss"
  version "0.0.1-rc.11"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/huseyinbabal/swiss/releases/download/0.0.1-rc.11/swiss_0.0.1-rc.11_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d478d2730b8e852e96cc7c73586be1b0c6b515902582277ec261b896be031798"

      def install
        bin.install "swiss"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/huseyinbabal/swiss/releases/download/0.0.1-rc.11/swiss_0.0.1-rc.11_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "7c5dfeaea94d00694723aeebc661aaee07f8454a33d220fcf6ebd14f95334019"

      def install
        bin.install "swiss"
      end
    end
  end
end
